///<reference path="../typings/tsd.d.ts"/>
/// <reference path="interfaces/interface.references.ts" />

//inject:ts
/// <reference path="app.ts" />
/// <reference path="constants.ts" />
/// <reference path="injections.ts" />
/// <reference path="min.references.ts" />
/// <reference path="registrations.ts" />
/// <reference path="routes.ts" />
/// <reference path="controllers/LobbyController.ts" />
/// <reference path="controllers/PlayerController.ts" />
/// <reference path="controllers/RankingController.ts" />
/// <reference path="controllers/SettingsController.ts" />
/// <reference path="controllers/GameController.ts" />
/// <reference path="controllers/AccountController.ts" />
/// <reference path="controllers/MenuController.ts" />
/// <reference path="filters/DurationFilter.ts" />
/// <reference path="filters/FormatFilter.ts" />
/// <reference path="interfaces/Framework.ts" />
/// <reference path="interfaces/Plugins.ts" />
/// <reference path="interfaces/Services.ts" />
/// <reference path="services/Navigation.ts" />
/// <reference path="services/Logger.ts" />
/// <reference path="services/Event.ts" />
/// <reference path="services/Urls.ts" />
/// <reference path="services/LoginProvider.ts" />
/// <reference path="services/PlayerProvider.ts" />
/// <reference path="services/LocalStorage.ts" />
/// <reference path="services/Converter.ts" />
/// <reference path="services/OpenLink.ts" />
/// <reference path="services/Strings.ts" />
/// <reference path="directives/Ranking.ts" />
/// <reference path="directives/Field.ts" />
/// <reference path="run-services/InternetConnectionWatcher.ts" />
/// <reference path="run-services/LocalizationConfig.ts" />
/// <reference path="run-services/ClearHistory.ts" />
/// <reference path="run-services/IonicConfig.ts" />
/// <reference path="interfaces/models/Models.ts" />
/// <reference path="interfaces/models/messages/Responses.ts" />
//end-inject:ts
